version: '3'

networks:
  backend:
    driver: bridge

services:
  rdbms:
    container_name: bigdata-rdbms
    image: postgres:alpine
    restart: always
    command: ['postgres', '-c', 'log_statement=all']
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: bigdata
      PGDATA: /var/lib/postgresql/data
  pgadmin:
    container_name: bigdata-pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: 12345678
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - ./pgadmin/data:/root/.pgadmin
    ports:
      - '8080:80'
    depends_on:
      - rdbms
    links:
      - rdbms:db
