version: "3"

networks:
  backend:
    driver: bridge

services:
  nosql:
    container_name: bigdata-nosql
    image: mongo:latest
    restart: always
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/init.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro # init script
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
  rdbms:
    container_name: bigdata-rdbms
    image: postgres:alpine
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
  pgadmin:
    container_name: bigdata-pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    volumes:
      - ./pgadmin/data:/root/.pgadmin
    ports:
      - "8080:${PGADMIN_LISTEN_PORT}"
    depends_on:
      - rdbms
    links:
      - rdbms:db
